apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: securepay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: your-dockerhub-user/auth-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: LOG_LEVEL
